### ISSUE TITLE
add the data for outline.shp

### ISSUE THREAD

**Issue by Rdataflow** [HAFL-WWI/pyFINT#2]
the necessary Geodata shall be provided:
- [ ] Kantone/outline.shp

**Comment by ChSchaller** [comment]
The mentioned geodata will not be provided due to license issues. However, the process is not dependent on this specific shapefile since the outlines respectively polygons are only used to reduce the detected trees to a specific perimeter. Possible sources for alternative data with the cantonal borders are mentioned in the new readme in the latest commit (f31a523ad21fc45c2b4480a1bd75263d99201848).
